version: '3.6'
services:
  # NestJS application service
  nestjs-app:
    image: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map the app's port to the host
    depends_on:
      - postgres-db # Ensure that the database service is running
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: posdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass

  # PostgreSQL database service
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: posdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432" # Map the database port to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: # Docker volume for PostgreSQL data persistence
