version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src