version: '3.6'
services:
  nestjs-app:
    image: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: posdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass

  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: posdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
